# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('Password', models.CharField(max_length=25)),
                ('Account', models.IntegerField(max_length=25)),
                ('Location', models.CharField(max_length=25)),
            ],
        ),
    ]
